<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>PeerOnQ.Downloads.Service</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PeerOnQ.Cloud.Application\PeerOnQ.Cloud.Application.csproj" />
    <ProjectReference Include="..\PeerOnQ.Cloud.Infrastructure\PeerOnQ.Cloud.Infrastructure.csproj" />
    <ProjectReference Include="..\PeerOnQ.Observability\PeerOnQ.Observability.csproj" />
    <ProjectReference Include="..\PeerOnQ.Shared.Contracts\PeerOnQ.Shared.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>
</Project>
