<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>PeerOnQ.Media</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PeerOnQ.Domain\PeerOnQ.Domain.csproj" />
    <ProjectReference Include="..\PeerOnQ.Application\PeerOnQ.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SIPSorcery" />
    <PackageReference Include="SIPSorceryMedia.Abstractions" />
    <PackageReference Include="SIPSorceryMedia.Encoders" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
</Project>
